Added Dockerfile and edited readme.md
PopFlamingo/Mannele pull request #23
Opened 2021-10-29 23:24 UTC by Reiaa

2021-11-04 22:15 UTC, PopFlamingo reviewed
Thanks a lot! This is the very first PR by an external contributor on this project! 😃 I think this is almost ready to merge, later I'll need to add more details about what the `STATS_SLOT_COUNT` env variable does exactly but for now I think setting it to one is indeed the safest default.

2021-11-04 22:15 UTC, PopFlamingo commented on Dockerfile
> +FROM node:16.11.1-bullseye-slim
Do we want to use node 16.11.1 specifically or would it make sense to use `node:latest`? I'm not sure what's best here.

2021-11-04 22:15 UTC, PopFlamingo commented on README.md
> +[MIT](https://choosealicense.com/licenses/mit/)
I'm not sure about linking an external source since the actual license file is in the repository.

2021-11-04 22:15 UTC, PopFlamingo commented on README.md
> +
Thank you for this, it was much needed! I suggest also adding details for installing on macOS.

2021-11-04 23:57 UTC, Reiaa commented on Dockerfile
> +FROM node:16.11.1-bullseye-slim
As for now, I've only tested with this version. Better safe than sorry.

2021-11-06 07:08 UTC, PopFlamingo requested changes
Just checked on my machine too and everything works great! 👍 I suggest keeping the license info unchanged for now. Once the few remaining lines of French are translated to English in the README I think we will be ready to merge 🙂

2021-11-06 07:08 UTC, PopFlamingo commented on README.md
> +[MIT](https://choosealicense.com/licenses/mit/)
I think it's best to keep it as it previously was @Reiaa

2021-11-06 07:08 UTC, PopFlamingo commented on Dockerfile
> +FROM node:16.11.1-bullseye-slim
Node doesn't seem to guarantee future Node versions are necessarily backwards indeed so it's probably best to keep it that way indeed 🙂

2021-11-06 10:33 UTC, Reiaa reviewed
I've edited the French lines, rolled back the MIT Licence section and tweaked a few words around to make it cleaner.

2021-11-06 10:33 UTC, Reiaa commented on README.md
> +[MIT](https://choosealicense.com/licenses/mit/)
Alright

2021-11-06 17:16 UTC, PopFlamingo approved these changes
Perfect! Thank you so much! It's great to know it will now be easier for everyone to use the bot without having to worry about environment inconsistencies.

2021-11-06 17:17 UTC, merged